/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Address;
import Business.Checkings;
import Business.Demographic;
import Business.DriverInfo;
import Business.Medical;
import Business.SavingsInfo;

/**
 *
 * @author admin
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Demographic demographic;
    Address address;
    SavingsInfo savings;
    Checkings checkings;
    DriverInfo driver;
    Medical med;
            
    public MainJFrame() {
        initComponents();
        demographic = new Demographic();
        address = new Address();
        savings = new SavingsInfo();
        checkings = new Checkings();
        driver = new DriverInfo();
        med = new Medical();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        LeftJPanel = new javax.swing.JPanel();
        createBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        createAddressBtn = new javax.swing.JButton();
        viewAddressBtn = new javax.swing.JButton();
        viewBtn5 = new javax.swing.JButton();
        createAcBtn = new javax.swing.JButton();
        viewBtn2 = new javax.swing.JButton();
        createBtn3 = new javax.swing.JButton();
        viewBtn3 = new javax.swing.JButton();
        createBtn4 = new javax.swing.JButton();
        viewBtn4 = new javax.swing.JButton();
        createBtn5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        createBtn6 = new javax.swing.JButton();
        RightJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setDividerLocation(150);

        createBtn.setBackground(new java.awt.Color(153, 153, 153));
        createBtn.setText("Create");
        createBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        viewBtn.setBackground(new java.awt.Color(153, 153, 153));
        viewBtn.setText("View");
        viewBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        createAddressBtn.setBackground(new java.awt.Color(153, 153, 153));
        createAddressBtn.setText("Create");
        createAddressBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createAddressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAddressBtnActionPerformed(evt);
            }
        });

        viewAddressBtn.setBackground(new java.awt.Color(153, 153, 153));
        viewAddressBtn.setText("View");
        viewAddressBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewAddressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAddressBtnActionPerformed(evt);
            }
        });

        viewBtn5.setBackground(new java.awt.Color(153, 153, 153));
        viewBtn5.setText("View");
        viewBtn5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtn5ActionPerformed(evt);
            }
        });

        createAcBtn.setBackground(new java.awt.Color(153, 153, 153));
        createAcBtn.setText("Create");
        createAcBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createAcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAcBtnActionPerformed(evt);
            }
        });

        viewBtn2.setBackground(new java.awt.Color(153, 153, 153));
        viewBtn2.setText("View");
        viewBtn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtn2ActionPerformed(evt);
            }
        });

        createBtn3.setBackground(new java.awt.Color(153, 153, 153));
        createBtn3.setText("Create");
        createBtn3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtn3ActionPerformed(evt);
            }
        });

        viewBtn3.setBackground(new java.awt.Color(153, 153, 153));
        viewBtn3.setText("View");
        viewBtn3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtn3ActionPerformed(evt);
            }
        });

        createBtn4.setBackground(new java.awt.Color(153, 153, 153));
        createBtn4.setText("Create");
        createBtn4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtn4ActionPerformed(evt);
            }
        });

        viewBtn4.setBackground(new java.awt.Color(153, 153, 153));
        viewBtn4.setText("View");
        viewBtn4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtn4ActionPerformed(evt);
            }
        });

        createBtn5.setBackground(new java.awt.Color(153, 153, 153));
        createBtn5.setText("Create");
        createBtn5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtn5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Demographic Information");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Address Information");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Savings A/c  Information");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Checking A/c  Information");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Driver's Information");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText(" Medical Information");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Generate Report");

        createBtn6.setBackground(new java.awt.Color(153, 153, 153));
        createBtn6.setText("Report");
        createBtn6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtn6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftJPanelLayout = new javax.swing.GroupLayout(LeftJPanel);
        LeftJPanel.setLayout(LeftJPanelLayout);
        LeftJPanelLayout.setHorizontalGroup(
            LeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LeftJPanelLayout.createSequentialGroup()
                        .addGroup(LeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(viewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addComponent(viewAddressBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addComponent(viewBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addComponent(viewBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addComponent(viewBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addComponent(createBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createAddressBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createAcBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(LeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(viewBtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(createBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LeftJPanelLayout.setVerticalGroup(
            LeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftJPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(createAddressBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewAddressBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createAcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addComponent(createBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(createBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(LeftJPanel);

        javax.swing.GroupLayout RightJPanelLayout = new javax.swing.GroupLayout(RightJPanel);
        RightJPanel.setLayout(RightJPanelLayout);
        RightJPanelLayout.setHorizontalGroup(
            RightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );
        RightJPanelLayout.setVerticalGroup(
            RightJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(RightJPanel);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
    CreateDemographicJPanel createDemographicJPanel = new CreateDemographicJPanel(demographic);
    jSplitPane1.setRightComponent(createDemographicJPanel);
        
    }//GEN-LAST:event_createBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        ViewDemographicJPanel viewdemographicJPanel = new ViewDemographicJPanel(demographic);
        jSplitPane1.setRightComponent(viewdemographicJPanel);
    }//GEN-LAST:event_viewBtnActionPerformed

    private void createAddressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAddressBtnActionPerformed
        // TODO add your handling code here:
        CreateAddressJPanel createAddressJPanel = new CreateAddressJPanel(address);
        jSplitPane1.setRightComponent(createAddressJPanel);
    }//GEN-LAST:event_createAddressBtnActionPerformed

    private void viewAddressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAddressBtnActionPerformed
        // TODO add your handling code here:
        ViewAddressJPanel viewAddressJPanel = new ViewAddressJPanel(address);
        jSplitPane1.setRightComponent(viewAddressJPanel);
    }//GEN-LAST:event_viewAddressBtnActionPerformed

    private void createAcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAcBtnActionPerformed
        // TODO add your handling code here:
        CreateSavingsAccInfoJPanel createSavingsAccInfo = new CreateSavingsAccInfoJPanel(savings);
        jSplitPane1.setRightComponent(createSavingsAccInfo);
    }//GEN-LAST:event_createAcBtnActionPerformed

    private void viewBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtn2ActionPerformed
        // TODO add your handling code here:
        ViewSavingsAccInfoJPanel  viewSavingsAccInfoJPanel = new ViewSavingsAccInfoJPanel(savings);
        jSplitPane1.setRightComponent(viewSavingsAccInfoJPanel);
    }//GEN-LAST:event_viewBtn2ActionPerformed

    private void createBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtn3ActionPerformed
        // TODO add your handling code here:
        CreateCheckingsAccInfoJPanel createCheckingsAccInfoJPanel = new CreateCheckingsAccInfoJPanel(checkings);
        jSplitPane1.setRightComponent(createCheckingsAccInfoJPanel);
    }//GEN-LAST:event_createBtn3ActionPerformed

    private void viewBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtn3ActionPerformed
        // TODO add your handling code here:
        ViewCheckingsInfoJPanel  viewCheckingsInfoJPanel = new ViewCheckingsInfoJPanel(checkings);
        jSplitPane1.setRightComponent(viewCheckingsInfoJPanel);
    }//GEN-LAST:event_viewBtn3ActionPerformed

    private void createBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtn4ActionPerformed
        CreateDriverInfoJPanel createDriverInfoJPanel = new CreateDriverInfoJPanel(driver);
        jSplitPane1.setRightComponent(createDriverInfoJPanel);
    }//GEN-LAST:event_createBtn4ActionPerformed

    private void viewBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtn4ActionPerformed
        // TODO add your handling code here:
         ViewDriverInfoJPanel viewDriverInfoJPanel = new ViewDriverInfoJPanel(driver);
         jSplitPane1.setRightComponent(viewDriverInfoJPanel);
    }//GEN-LAST:event_viewBtn4ActionPerformed

    private void createBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtn5ActionPerformed
        // TODO add your handling code here:
         CreateMedicalInfoJPanel createMedicalInfoJPanel = new CreateMedicalInfoJPanel(med);
        jSplitPane1.setRightComponent(createMedicalInfoJPanel);
    }//GEN-LAST:event_createBtn5ActionPerformed

    private void viewBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtn5ActionPerformed
        // TODO add your handling code here:
         ViewMedicalInfoJPanel viewMedicalInfoJPanel = new ViewMedicalInfoJPanel(med);
        jSplitPane1.setRightComponent(viewMedicalInfoJPanel);
    }//GEN-LAST:event_viewBtn5ActionPerformed

    private void createBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtn6ActionPerformed
        // TODO add your handling code here: 
        ReportJPanel rp = new ReportJPanel(demographic,address,savings,checkings,driver,med);
        jSplitPane1.setRightComponent(rp);
    }//GEN-LAST:event_createBtn6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LeftJPanel;
    private javax.swing.JPanel RightJPanel;
    private javax.swing.JButton createAcBtn;
    private javax.swing.JButton createAddressBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton createBtn3;
    private javax.swing.JButton createBtn4;
    private javax.swing.JButton createBtn5;
    private javax.swing.JButton createBtn6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton viewAddressBtn;
    private javax.swing.JButton viewBtn;
    private javax.swing.JButton viewBtn2;
    private javax.swing.JButton viewBtn3;
    private javax.swing.JButton viewBtn4;
    private javax.swing.JButton viewBtn5;
    // End of variables declaration//GEN-END:variables
}
